apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todo-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
